# Generated by Django 6.0.3 on 2026-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('total_applications', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_interviews', models.IntegerField(default=0)),
                ('response_rate', models.FloatField(default=0.0)),
                ('interview_conversion_rate', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
    ]
