# Generated by Django 6.0.3 on 2026-03-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='weeklyanalytics',
            index=models.Index(fields=['user', '-week_start_date'], name='analytics_w_user_id_ceda3f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyanalytics',
            index=models.Index(fields=['week_start_date'], name='analytics_w_week_st_8a8406_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyanalytics',
            unique_together={('user', 'week_start_date')},
        ),
    ]
